### PR TITLE
fix typo with print function in usage

### PR DESCRIPTION
**Pull request by grisaitis**

### CODE REVIEW

**Comment by CholoTook** [comment]
Why are checks failing for this typo fix?

**Comment by CholoTook** [comment]
If I had to guess, looking at the log, the test that is running is doing too much work. It's grabbing a very large file (or files) with many samples... (as far as I can tell).

Where is the test written? (Sorry for being lazy ;-)

**Comment by grisaitis** [comment]
haha i have no idea. good catch and investigation, though.

also this isn't very important, so i might delete if i see in a few months that it's stale

**Comment by CholoTook** [comment]
Seems a shame to throw away any contribution. The project seems to be
making a lot of effort to gather community input, and this is exactly the
sort of small thing that builds a community.

Lets see and hope that the maintainer notices soon :-)

**Comment by guma44** [comment]
Hey, thanks a lot. Yeah, the tests need to be rewritten a bit. I like such a small fixes. I agree - it is a good start and makes project better even if this is just a small thing.

**Pull request merged**
