### PR TITLE
Python 3 Compatibility

### LINKED ISSUE #4: python 2.7 only?
Is this package for supported for python 2.7 only? Might be a good idea to include that in the readme

### PR DESCRIPTION
**Pull request by tychobismeijer**
This was tested on reading a gse SOFT file. Also, no more tests are failing in python 2 and python 3 than before. Fixes #4

### CODE REVIEW

**Comment by guma44** [comment]
This is really good improvement. I wanted to make it for the new release as anyway python 2 support is ending and everybody is moving to python 3.

**Comment by guma44** [comment]
I already pushed it to pypi :)

**Comment by j-berg** [comment]
It looks from this thread that geoparse if python 3 compatible, but I am having an issue with conda installing where it says it only works with python 3.5*. Looks from the Travis build info, its being tested on 3.7-dev. Any idea as to why it may only be compatible with 3.5 (at least with the conda install?
`70.44s$ conda install --yes -c gusdunn geoparse
Fetching package metadata .............
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - geoparse -> python 3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
The command "conda install --yes -c gusdunn geoparse" failed and exited with 1 during .`

**Comment by guma44** [comment]
Hi, at least for my setup it is compatible. All the test are running. It could be something with the conda environment. I am not familiar with it. Can it be that the conda package requires something else than pip?

**Comment by j-berg** [comment]
I looked into it more -- still no solution for the conda build in Travis, but it seems to work with all versions of python when pip installing geoparse and other dependencies.

**Comment by guma44** [comment]
This looks like a conda problem. Maybe you would try to contact the uploader for the package (`gusdunn`)?

**Pull request merged**
